name: sofolit
description: "Success begins here"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  http: ^1.3.0
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  get: ^5.0.0-release-candidate-9.3.2
  icon_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ador
      fonts:
        - asset: assets/fonts/ador_bold.ttf
          weight: 700
        - asset: assets/fonts/ador_light.ttf
          weight: 500
    - family: Noto
      fonts:
        - asset: assets/fonts/noto_regular.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
